"""add company_id to email_outbox

Revision ID: 74f46c98d2fb
Revises: 16487a43b825
Create Date: 2026-02-23 09:04:50.053779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f46c98d2fb'
down_revision = '16487a43b825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_types_prefix'))
        batch_op.create_index(batch_op.f('ix_code_types_prefix'), ['prefix'], unique=True)

    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_email_outbox_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_email_outbox_company_id'))
        batch_op.drop_column('company_id')

    with op.batch_alter_table('code_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_types_prefix'))
        batch_op.create_index(batch_op.f('ix_code_types_prefix'), ['prefix'], unique=False)

    # ### end Alembic commands ###
