"""initial just-click migration

Revision ID: f9023371e122
Revises: 
Create Date: 2026-02-03 21:49:46.162121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9023371e122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_actions_enabled', ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_actions_updated_at'), ['updated_at'], unique=False)

    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True, comment='Short code, e.g. CMCP, UOS, etc.'),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True, comment='Object-storage key/path for logo'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='IANA timezone string (e.g., Africa/Mogadishu)'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_companies_code'),
    sa.UniqueConstraint('name', name='uq_companies_name')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_contact_phone'), ['contact_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_logo_key'), ['logo_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_updated_at'), ['updated_at'], unique=False)

    op.create_table('doc_types',
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_types_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_types_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_doc_types_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_doctype_enabled', ['is_enabled'], unique=False)

    op.create_table('roles',
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_roles_enabled', ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('STUDENT', 'TEACHER', 'STAFF', 'ADMIN', name='user_type_enum'), nullable=False),
    sa.Column('is_system_owner', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_users_enabled', ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_system_owner'), ['is_system_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_type'), ['user_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('edu_academic_years',
    sa.Column('name', sa.String(length=20), nullable=False, comment='e.g. 2025/2026'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_edu_years_company_name')
    )
    with op.batch_alter_table('edu_academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_academic_years_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_academic_years_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_academic_years_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_academic_years_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_academic_years_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_classrooms',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_classrooms_company_name')
    )
    with op.batch_alter_table('edu_classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_classrooms_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_classrooms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_classrooms_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_classrooms_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_classrooms_room_number'), ['room_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_classrooms_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_faculties',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_edu_faculties_company_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_edu_faculties_company_name')
    )
    with op.batch_alter_table('edu_faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_faculties_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_faculties_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_faculties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_faculties_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_faculties_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_faculties_updated_at'), ['updated_at'], unique=False)

    op.create_table('permissions',
    sa.Column('doctype_id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctype_id'], ['doc_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctype_id', 'action_id', name='uq_perm_doctype_action')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('ix_permissions_action', ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_permissions_doctype', ['doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_doctype_id'), ['doctype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_affiliations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_company_owner', sa.Boolean(), nullable=False),
    sa.Column('linked_entity_type', sa.Enum('STUDENT_PROFILE', 'STAFF_PROFILE', name='linked_entity_type_enum'), nullable=True),
    sa.Column('linked_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(linked_entity_type is null and linked_entity_id is null) OR (linked_entity_type is not null and linked_entity_id is not null)', name='ck_user_affiliation_linked_entity_pair'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_affiliation_user_company')
    )
    with op.batch_alter_table('user_affiliations', schema=None) as batch_op:
        batch_op.create_index('ix_user_aff_company_user', ['company_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_is_company_owner'), ['is_company_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_linked_entity_id'), ['linked_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_linked_entity_type'), ['linked_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliations_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'role_id', name='uq_user_roles_company_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_user_roles_company_role', ['company_id', 'role_id'], unique=False)
        batch_op.create_index('ix_user_roles_company_user', ['company_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('edu_departments',
    sa.Column('faculty_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['edu_faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_edu_depts_company_code'),
    sa.UniqueConstraint('company_id', 'faculty_id', 'name', name='uq_edu_depts_company_faculty_name')
    )
    with op.batch_alter_table('edu_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_departments_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_departments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_departments_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_departments_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_departments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_departments_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_semesters',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False, comment='1..8 (or any number your university uses)'),
    sa.Column('name', sa.String(length=50), nullable=True, comment="Optional label e.g. 'Semester 1'"),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('number >= 1', name='ck_edu_sem_number_min'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['edu_academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'academic_year_id', 'number', name='uq_edu_sem_company_year_number')
    )
    with op.batch_alter_table('edu_semesters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_semesters_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_semesters_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_semesters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_semesters_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_semesters_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_semesters_updated_at'), ['updated_at'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_perm')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_role_permissions_perm', ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index('ix_role_permissions_role', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_courses',
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('semester_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['edu_departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['edu_semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_edu_courses_company_code'),
    sa.UniqueConstraint('company_id', 'semester_id', 'department_id', 'title', name='uq_edu_course_scope_title')
    )
    with op.batch_alter_table('edu_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_courses_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_courses_updated_at'), ['updated_at'], unique=False)

    op.create_table('staff_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('staff_id', sa.String(length=60), nullable=True, comment='Optional university staff/teacher ID'),
    sa.Column('faculty_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['edu_departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['edu_faculties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'staff_id', name='uq_staff_profiles_company_staff_id')
    )
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('student_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('student_id', sa.String(length=60), nullable=False, comment='University-issued Student ID'),
    sa.Column('faculty_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.BigInteger(), nullable=True),
    sa.Column('semester_id', sa.BigInteger(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['edu_classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['edu_departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['edu_faculties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['edu_semesters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_id', name='uq_student_profiles_company_student_id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('edu_chapters',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('number >= 1', name='ck_edu_chapters_number_min'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'course_id', 'number', name='uq_edu_chapters_course_number')
    )
    with op.batch_alter_table('edu_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_chapters_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_chapters_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_chapters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_chapters_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_chapters_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_chapters_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_chapters_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_materials',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('material_type', sa.Enum('SLIDES', 'PDF', 'DOC', 'VIDEO', 'LINK', 'OTHER', name='edu_material_type_enum'), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('slide_count', sa.Integer(), nullable=True),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='e.g. ["Learn Syntax", "Understand Loops"]'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('is_downloadable', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(file_size_mb is null) OR (file_size_mb >= 0)', name='ck_edu_material_size_min'),
    sa.CheckConstraint('(page_count is null) OR (page_count >= 1)', name='ck_edu_material_page_min'),
    sa.CheckConstraint('(slide_count is null) OR (slide_count >= 1)', name='ck_edu_material_slide_min'),
    sa.ForeignKeyConstraint(['chapter_id'], ['edu_chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['edu_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'course_id', 'chapter_id', 'title', name='uq_edu_materials_scope_title')
    )
    with op.batch_alter_table('edu_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_materials_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index('ix_edu_materials_company_course', ['company_id', 'course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_is_downloadable'), ['is_downloadable'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_material_type'), ['material_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_materials_updated_at'), ['updated_at'], unique=False)

    op.create_table('edu_material_interactions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['edu_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'material_id', name='uq_user_material_interaction')
    )
    with op.batch_alter_table('edu_material_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edu_material_interactions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_material_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_material_interactions_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_material_interactions_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_material_interactions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edu_material_interactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_interactions_company_material', ['company_id', 'material_id'], unique=False)
        batch_op.create_index('ix_interactions_company_user', ['company_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edu_material_interactions', schema=None) as batch_op:
        batch_op.drop_index('ix_interactions_company_user')
        batch_op.drop_index('ix_interactions_company_material')
        batch_op.drop_index(batch_op.f('ix_edu_material_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_edu_material_interactions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_material_interactions_material_id'))
        batch_op.drop_index(batch_op.f('ix_edu_material_interactions_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_edu_material_interactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_material_interactions_company_id'))

    op.drop_table('edu_material_interactions')
    with op.batch_alter_table('edu_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_materials_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_title'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_material_type'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_is_downloadable'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_course_id'))
        batch_op.drop_index(batch_op.f('ix_edu_materials_company_id'))
        batch_op.drop_index('ix_edu_materials_company_course')
        batch_op.drop_index(batch_op.f('ix_edu_materials_chapter_id'))

    op.drop_table('edu_materials')
    with op.batch_alter_table('edu_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_chapters_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_chapters_title'))
        batch_op.drop_index(batch_op.f('ix_edu_chapters_number'))
        batch_op.drop_index(batch_op.f('ix_edu_chapters_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_chapters_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_chapters_course_id'))
        batch_op.drop_index(batch_op.f('ix_edu_chapters_company_id'))

    op.drop_table('edu_chapters')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_semester_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_full_name'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_department_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_company_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_classroom_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_full_name'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_department_id'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_company_id'))

    op.drop_table('staff_profiles')
    with op.batch_alter_table('edu_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_courses_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_title'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_semester_id'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_department_id'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_courses_code'))

    op.drop_table('edu_courses')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index('ix_role_permissions_role')
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))
        batch_op.drop_index('ix_role_permissions_perm')
        batch_op.drop_index(batch_op.f('ix_role_permissions_created_at'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('edu_semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_semesters_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_semesters_number'))
        batch_op.drop_index(batch_op.f('ix_edu_semesters_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_semesters_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_semesters_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_semesters_academic_year_id'))

    op.drop_table('edu_semesters')
    with op.batch_alter_table('edu_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_departments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_departments_name'))
        batch_op.drop_index(batch_op.f('ix_edu_departments_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_departments_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_edu_departments_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_departments_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_departments_code'))

    op.drop_table('edu_departments')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_user_roles_created_at'))
        batch_op.drop_index('ix_user_roles_company_user')
        batch_op.drop_index('ix_user_roles_company_role')
        batch_op.drop_index(batch_op.f('ix_user_roles_company_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('user_affiliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_affiliations_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_linked_entity_type'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_linked_entity_id'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_is_primary'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_is_company_owner'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_affiliations_company_id'))
        batch_op.drop_index('ix_user_aff_company_user')

    op.drop_table('user_affiliations')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_permissions_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_permissions_doctype_id'))
        batch_op.drop_index('ix_permissions_doctype')
        batch_op.drop_index(batch_op.f('ix_permissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_permissions_action_id'))
        batch_op.drop_index('ix_permissions_action')

    op.drop_table('permissions')
    with op.batch_alter_table('edu_faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_faculties_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_faculties_name'))
        batch_op.drop_index(batch_op.f('ix_edu_faculties_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_faculties_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_faculties_company_id'))
        batch_op.drop_index(batch_op.f('ix_edu_faculties_code'))

    op.drop_table('edu_faculties')
    with op.batch_alter_table('edu_classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_classrooms_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_classrooms_room_number'))
        batch_op.drop_index(batch_op.f('ix_edu_classrooms_name'))
        batch_op.drop_index(batch_op.f('ix_edu_classrooms_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_classrooms_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_classrooms_company_id'))

    op.drop_table('edu_classrooms')
    with op.batch_alter_table('edu_academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edu_academic_years_updated_at'))
        batch_op.drop_index(batch_op.f('ix_edu_academic_years_name'))
        batch_op.drop_index(batch_op.f('ix_edu_academic_years_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_edu_academic_years_created_at'))
        batch_op.drop_index(batch_op.f('ix_edu_academic_years_company_id'))

    op.drop_table('edu_academic_years')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_user_type'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_is_system_owner'))
        batch_op.drop_index(batch_op.f('ix_users_is_enabled'))
        batch_op.drop_index('ix_users_enabled')
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_is_enabled'))
        batch_op.drop_index('ix_roles_enabled')
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('doc_types', schema=None) as batch_op:
        batch_op.drop_index('ix_doctype_enabled')
        batch_op.drop_index(batch_op.f('ix_doc_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_doc_types_name'))
        batch_op.drop_index(batch_op.f('ix_doc_types_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_doc_types_created_at'))

    op.drop_table('doc_types')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_logo_key'))
        batch_op.drop_index(batch_op.f('ix_companies_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_companies_created_at'))
        batch_op.drop_index(batch_op.f('ix_companies_country'))
        batch_op.drop_index(batch_op.f('ix_companies_contact_phone'))
        batch_op.drop_index(batch_op.f('ix_companies_contact_email'))
        batch_op.drop_index(batch_op.f('ix_companies_code'))
        batch_op.drop_index(batch_op.f('ix_companies_city'))

    op.drop_table('companies')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_actions_name'))
        batch_op.drop_index(batch_op.f('ix_actions_is_enabled'))
        batch_op.drop_index('ix_actions_enabled')
        batch_op.drop_index(batch_op.f('ix_actions_created_at'))

    op.drop_table('actions')
    # ### end Alembic commands ###
