// libs/getAllMaterials.js
const materials = [
  // Semester 1 Materials
  {
    id: 1,
    title: "Introduction to Programming (Chapter 1)",
    semester: 1,
    subject: "Programming Fundamentals",
    chapter: "Chapter 1: Basics of Programming",
    fileType: "pdf",
    fileUrl: "/materials/sem1/intro-programming.pdf",
    thumbnail: null,
    size: "2.3 MB",
    pages: 45,
    uploadDate: "2025-01-15",
    downloads: 234,
  },
  {
    id: 2,
    title: "Programming Fundamentals - Lecture Slides",
    semester: 1,
    subject: "Programming Fundamentals",
    chapter: "Chapter 2: Control Structures",
    fileType: "pptx",
    fileUrl: "/materials/sem1/programming-fundamentals.pptx",
    thumbnail: null,
    size: "5.1 MB",
    slides: 67,
    uploadDate: "2025-01-20",
    downloads: 189,
  },
  {
    id: 3,
    title: "Introduction to Algorithms",
    semester: 1,
    subject: "Algorithms",
    chapter: "Chapter 3: Algorithm Basics",
    fileType: "pdf",
    fileUrl: "/materials/sem1/intro-algorithms.pdf",
    thumbnail: null,
    size: "3.7 MB",
    pages: 52,
    uploadDate: "2025-01-25",
    downloads: 156,
  },

  // Semester 2 Materials
  {
    id: 4,
    title: "Data Structures - Linked Lists",
    semester: 2,
    subject: "Data Structures",
    chapter: "Chapter 3: Linked Lists",
    fileType: "pptx",
    fileUrl: "/materials/sem2/linked-lists.pptx",
    thumbnail: null,
    size: "4.2 MB",
    slides: 78,
    uploadDate: "2025-02-10",
    downloads: 312,
  },
  {
    id: 5,
    title: "Stacks and Queues",
    semester: 2,
    subject: "Data Structures",
    chapter: "Chapter 4: Stacks & Queues",
    fileType: "pdf",
    fileUrl: "/materials/sem2/stacks-queues.pdf",
    thumbnail: null,
    size: "2.8 MB",
    pages: 38,
    uploadDate: "2025-02-15",
    downloads: 278,
  },
  {
    id: 6,
    title: "Trees and Binary Search Trees",
    semester: 2,
    subject: "Data Structures",
    chapter: "Chapter 5: Trees",
    fileType: "pptx",
    fileUrl: "/materials/sem2/trees.pptx",
    thumbnail: null,
    size: "6.3 MB",
    slides: 95,
    uploadDate: "2025-02-20",
    downloads: 245,
  },

  // Semester 3 Materials
  {
    id: 7,
    title: "Database Design Fundamentals",
    semester: 3,
    subject: "Database Systems",
    chapter: "Chapter 1: Introduction to DBMS",
    fileType: "pdf",
    fileUrl: "/materials/sem3/database-design.pdf",
    thumbnail: null,
    size: "3.1 MB",
    pages: 62,
    uploadDate: "2025-03-05",
    downloads: 421,
  },
  {
    id: 8,
    title: "SQL Queries and Joins",
    semester: 3,
    subject: "Database Systems",
    chapter: "Chapter 3: SQL Fundamentals",
    fileType: "pdf",
    fileUrl: "/materials/sem3/sql-queries.pdf",
    thumbnail: null,
    size: "4.5 MB",
    pages: 58,
    uploadDate: "2025-03-10",
    downloads: 387,
  },
  {
    id: 9,
    title: "Database Normalization",
    semester: 3,
    subject: "Database Systems",
    chapter: "Chapter 4: Normalization",
    fileType: "pptx",
    fileUrl: "/materials/sem3/normalization.pptx",
    thumbnail: null,
    size: "3.9 MB",
    slides: 72,
    uploadDate: "2025-03-15",
    downloads: 298,
  },

  // Semester 4 Materials
  {
    id: 10,
    title: "Operating Systems - Process Management",
    semester: 4,
    subject: "Operating Systems",
    chapter: "Chapter 2: Processes",
    fileType: "pdf",
    fileUrl: "/materials/sem4/process-management.pdf",
    thumbnail: null,
    size: "3.4 MB",
    pages: 48,
    uploadDate: "2025-04-01",
    downloads: 512,
  },
  {
    id: 11,
    title: "Memory Management",
    semester: 4,
    subject: "Operating Systems",
    chapter: "Chapter 4: Memory",
    fileType: "pptx",
    fileUrl: "/materials/sem4/memory-management.pptx",
    thumbnail: null,
    size: "5.7 MB",
    slides: 88,
    uploadDate: "2025-04-05",
    downloads: 467,
  },
];

const getAllMaterials = () => materials;

export default getAllMaterials;