// Mock data for Academic management pages

export const facultiesData = [
  {
    id: "FAC-001",
    name: "Faculty of Engineering",
    dean: "Dr. Ahmed Hassan",
    departments: 6,
    students: 1240,
    established: "2001",
    status: "Active",
  },
  {
    id: "FAC-002",
    name: "Faculty of Science",
    dean: "Dr. Fatima Al-Zahra",
    departments: 5,
    students: 980,
    established: "1998",
    status: "Active",
  },
  {
    id: "FAC-003",
    name: "Faculty of Business Administration",
    dean: "Prof. Mohamed Salah",
    departments: 4,
    students: 1560,
    established: "2003",
    status: "Active",
  },
  {
    id: "FAC-004",
    name: "Faculty of Medicine",
    dean: "Dr. Sarah Johnson",
    departments: 8,
    students: 740,
    established: "1995",
    status: "Active",
  },
  {
    id: "FAC-005",
    name: "Faculty of Arts & Humanities",
    dean: "Prof. Ali Ibrahim",
    departments: 7,
    students: 620,
    established: "2000",
    status: "Active",
  },
  {
    id: "FAC-006",
    name: "Faculty of Law",
    dean: "Dr. Nadia Karim",
    departments: 3,
    students: 430,
    established: "2008",
    status: "Inactive",
  },
  {
    id: "FAC-007",
    name: "Faculty of Education",
    dean: "Prof. Omar Yusuf",
    departments: 5,
    students: 870,
    established: "2005",
    status: "Active",
  },
  {
    id: "FAC-008",
    name: "Faculty of Information Technology",
    dean: "Dr. Layla Nour",
    departments: 4,
    students: 1100,
    established: "2010",
    status: "Active",
  },
];

export const facultiesColumns = [
  { key: "id", label: "ID", width: "w-28" },
  { key: "name", label: "Faculty Name", width: "flex-1", bold: true },
  { key: "dean", label: "Dean", width: "w-44" },
  { key: "departments", label: "Departments", width: "w-32", align: "center" },
  { key: "students", label: "Students", width: "w-28", align: "center" },
  { key: "established", label: "Est.", width: "w-20", align: "center" },
  { key: "status", label: "Status", width: "w-24", type: "badge" },
];

// ─── Departments ──────────────────────────────────────────────────────────────

export const departmentsData = [
  {
    id: "DEP-001",
    name: "Computer Science",
    faculty: "Engineering",
    head: "Dr. Khalid Al-Rashid",
    courses: 24,
    students: 420,
    status: "Active",
  },
  {
    id: "DEP-002",
    name: "Electrical Engineering",
    faculty: "Engineering",
    head: "Dr. Youssef Benali",
    courses: 20,
    students: 310,
    status: "Active",
  },
  {
    id: "DEP-003",
    name: "Civil Engineering",
    faculty: "Engineering",
    head: "Prof. Reem Nasser",
    courses: 18,
    students: 285,
    status: "Active",
  },
  {
    id: "DEP-004",
    name: "Mathematics",
    faculty: "Science",
    head: "Dr. Hana Ibrahim",
    courses: 15,
    students: 198,
    status: "Active",
  },
  {
    id: "DEP-005",
    name: "Physics",
    faculty: "Science",
    head: "Prof. Samir Rahman",
    courses: 16,
    students: 212,
    status: "Active",
  },
  {
    id: "DEP-006",
    name: "Marketing",
    faculty: "Business Administration",
    head: "Dr. Amira Hassan",
    courses: 14,
    students: 390,
    status: "Active",
  },
  {
    id: "DEP-007",
    name: "Finance",
    faculty: "Business Administration",
    head: "Prof. Tariq Mansour",
    courses: 16,
    students: 365,
    status: "Active",
  },
  {
    id: "DEP-008",
    name: "Anatomy",
    faculty: "Medicine",
    head: "Dr. Nour El-Din",
    courses: 10,
    students: 180,
    status: "Active",
  },
  {
    id: "DEP-009",
    name: "Arabic Literature",
    faculty: "Arts & Humanities",
    head: "Prof. Laila Zamani",
    courses: 12,
    students: 145,
    status: "Inactive",
  },
  {
    id: "DEP-010",
    name: "Software Engineering",
    faculty: "Information Technology",
    head: "Dr. Basel Kareem",
    courses: 22,
    students: 530,
    status: "Active",
  },
];

export const departmentsColumns = [
  { key: "id", label: "ID", width: "w-28" },
  { key: "name", label: "Department", width: "flex-1", bold: true },
  { key: "faculty", label: "Faculty", width: "w-44" },
  { key: "head", label: "Head", width: "w-40" },
  { key: "courses", label: "Courses", width: "w-24", align: "center" },
  { key: "students", label: "Students", width: "w-24", align: "center" },
  { key: "status", label: "Status", width: "w-24", type: "badge" },
];

// ─── Courses ──────────────────────────────────────────────────────────────────

export const coursesData = [
  {
    id: "CRS-001",
    name: "Introduction to Programming",
    code: "CS101",
    department: "Computer Science",
    instructor: "Dr. Khalid Al-Rashid",
    credits: 3,
    students: 120,
    semester: "Fall 2024",
    status: "Active",
  },
  {
    id: "CRS-002",
    name: "Data Structures & Algorithms",
    code: "CS201",
    department: "Computer Science",
    instructor: "Dr. Layla Nour",
    credits: 4,
    students: 98,
    semester: "Spring 2025",
    status: "Active",
  },
  {
    id: "CRS-003",
    name: "Database Management Systems",
    code: "CS301",
    department: "Computer Science",
    instructor: "Prof. Basel Kareem",
    credits: 3,
    students: 85,
    semester: "Fall 2024",
    status: "Active",
  },
  {
    id: "CRS-004",
    name: "Circuit Theory",
    code: "EE101",
    department: "Electrical Engineering",
    instructor: "Dr. Youssef Benali",
    credits: 4,
    students: 72,
    semester: "Fall 2024",
    status: "Active",
  },
  {
    id: "CRS-005",
    name: "Calculus I",
    code: "MATH101",
    department: "Mathematics",
    instructor: "Dr. Hana Ibrahim",
    credits: 3,
    students: 155,
    semester: "Spring 2025",
    status: "Active",
  },
  {
    id: "CRS-006",
    name: "Marketing Fundamentals",
    code: "MKT101",
    department: "Marketing",
    instructor: "Dr. Amira Hassan",
    credits: 3,
    students: 140,
    semester: "Spring 2025",
    status: "Active",
  },
  {
    id: "CRS-007",
    name: "Financial Accounting",
    code: "FIN101",
    department: "Finance",
    instructor: "Prof. Tariq Mansour",
    credits: 3,
    students: 130,
    semester: "Fall 2024",
    status: "Active",
  },
  {
    id: "CRS-008",
    name: "Operating Systems",
    code: "CS401",
    department: "Computer Science",
    instructor: "Dr. Omar Yusuf",
    credits: 3,
    students: 76,
    semester: "Fall 2024",
    status: "Draft",
  },
  {
    id: "CRS-009",
    name: "Software Engineering",
    code: "SE301",
    department: "Software Engineering",
    instructor: "Dr. Basel Kareem",
    credits: 4,
    students: 88,
    semester: "Spring 2025",
    status: "Active",
  },
  {
    id: "CRS-010",
    name: "Quantum Physics",
    code: "PHY301",
    department: "Physics",
    instructor: "Prof. Samir Rahman",
    credits: 3,
    students: 45,
    semester: "Fall 2024",
    status: "Inactive",
  },
  {
    id: "CRS-011",
    name: "Web Development",
    code: "CS501",
    department: "Computer Science",
    instructor: "Dr. Layla Nour",
    credits: 3,
    students: 110,
    semester: "Spring 2025",
    status: "Active",
  },
  {
    id: "CRS-012",
    name: "Structural Analysis",
    code: "CE201",
    department: "Civil Engineering",
    instructor: "Prof. Reem Nasser",
    credits: 4,
    students: 65,
    semester: "Fall 2024",
    status: "Active",
  },
];

export const coursesColumns = [
  { key: "id", label: "ID", width: "w-24" },
  { key: "code", label: "Code", width: "w-24" },
  { key: "name", label: "Course Name", width: "flex-1", bold: true },
  { key: "department", label: "Department", width: "w-44" },
  { key: "instructor", label: "Instructor", width: "w-40" },
  { key: "credits", label: "Credits", width: "w-20", align: "center" },
  { key: "students", label: "Students", width: "w-24", align: "center" },
  { key: "semester", label: "Semester", width: "w-32" },
  { key: "status", label: "Status", width: "w-24", type: "badge" },
];

// ─── Materials ──────────────────────────────────────────────────────────────────

export const materialsData = [
  {
    id: "MAT-001",
    title: "Introduction to Python – Lecture Slides",
    course: "CS101",
    type: "Slides",
    uploadedBy: "Dr. Khalid Al-Rashid",
    size: "4.2 MB",
    uploadDate: "2024-09-05",
    status: "Published",
  },
  {
    id: "MAT-002",
    title: "Data Structures – Lab Manual",
    course: "CS201",
    type: "PDF",
    uploadedBy: "Dr. Layla Nour",
    size: "8.7 MB",
    uploadDate: "2024-09-12",
    status: "Published",
  },
  {
    id: "MAT-003",
    title: "Database Design Patterns",
    course: "CS301",
    type: "PDF",
    uploadedBy: "Prof. Basel Kareem",
    size: "3.1 MB",
    uploadDate: "2024-10-01",
    status: "Published",
  },
  {
    id: "MAT-004",
    title: "Circuit Theory – Problem Sets",
    course: "EE101",
    type: "PDF",
    uploadedBy: "Dr. Youssef Benali",
    size: "1.9 MB",
    uploadDate: "2024-09-20",
    status: "Published",
  },
  {
    id: "MAT-005",
    title: "Calculus – Formula Sheet",
    course: "MATH101",
    type: "Slides",
    uploadedBy: "Dr. Hana Ibrahim",
    size: "0.8 MB",
    uploadDate: "2024-09-08",
    status: "Published",
  },
  {
    id: "MAT-006",
    title: "Marketing Strategy – Case Studies",
    course: "MKT101",
    type: "Video",
    uploadedBy: "Dr. Amira Hassan",
    size: "220 MB",
    uploadDate: "2024-10-15",
    status: "Draft",
  },
  {
    id: "MAT-007",
    title: "Financial Accounting Workbook",
    course: "FIN101",
    type: "PDF",
    uploadedBy: "Prof. Tariq Mansour",
    size: "5.5 MB",
    uploadDate: "2024-09-30",
    status: "Published",
  },
  {
    id: "MAT-008",
    title: "OS Concepts – Chapter 1-5",
    course: "CS401",
    type: "PDF",
    uploadedBy: "Dr. Omar Yusuf",
    size: "12.3 MB",
    uploadDate: "2024-11-02",
    status: "Draft",
  },
  {
    id: "MAT-009",
    title: "Web Dev – React Tutorial Video",
    course: "CS501",
    type: "Video",
    uploadedBy: "Dr. Layla Nour",
    size: "450 MB",
    uploadDate: "2025-01-18",
    status: "Published",
  },
  {
    id: "MAT-010",
    title: "Structural Analysis Diagrams",
    course: "CE201",
    type: "Slides",
    uploadedBy: "Prof. Reem Nasser",
    size: "6.8 MB",
    uploadDate: "2024-09-25",
    status: "Published",
  },
];

export const materialsColumns = [
  { key: "id", label: "ID", width: "w-24" },
  { key: "title", label: "Title", width: "flex-1", bold: true },
  { key: "course", label: "Course", width: "w-24", align: "center" },
  { key: "type", label: "Type", width: "w-24", type: "typeBadge" },
  { key: "uploadedBy", label: "Uploaded By", width: "w-44" },
  { key: "size", label: "Size", width: "w-24", align: "center" },
  { key: "uploadDate", label: "Date", width: "w-28" },
  { key: "status", label: "Status", width: "w-24", type: "badge" },
];
